feat: expanding gha scopes to lint/format/check locks (#88)
* feat: expanding gha scopes to lint/format/check locks

* fix: format/lint checks

* fix: lint/format examples

* fix: added lint:check and format:check to examples/typescript

diff --git a/.github/workflows/check_package_lock.yml b/.github/workflows/check_package_lock.yml
--- a/.github/workflows/check_package_lock.yml
+++ b/.github/workflows/check_package_lock.yml
@@ -27,3 +27,29 @@ jobs:
             git diff pnpm-lock.yaml
             exit 1
           fi
+
+  check-package-lock-examples-typescript:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Setup pnpm
+        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
+        with:
+          run_install: false
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+          cache: "pnpm"
+          cache-dependency-path: ./examples/typescript
+
+      - name: Check if pnpm-lock.yaml changed
+        working-directory: ./examples/typescript
+        run: |
+          pnpm install
+          if [ -n "$(git diff pnpm-lock.yaml)" ]; then
+            echo "Error: pnpm-lock.yaml was modified after running pnpm install. Please commit the updated pnpm-lock.yaml file."
+            git diff pnpm-lock.yaml
+            exit 1
+          fi
